# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[
        ('node.exe', '.'),
        ('cloudflared.exe', '.')
    ],
    datas=[
        # Assets — HTML, CSS, JS, images, fonts, mobile
        ('app/assets', 'assets'),
        # WhatsApp Node.js scripts
        ('app/services/whatsapp', 'app/services/whatsapp'),
        # Node.js dependencies
        ('node_modules', 'node_modules'),
        # Puppeteer browser cache
        ('.puppeteer_cache', '.puppeteer_cache'),
    ],
    hiddenimports=[
        # ── PySide6 / Qt ──────────────────────────────────────────────
        'PySide6.QtWidgets',
        'PySide6.QtGui',
        'PySide6.QtCore',
        'PySide6.QtWebEngineWidgets',
        'PySide6.QtWebEngineCore',
        'PySide6.QtWebChannel',
        'PySide6.QtNetwork',
        'PySide6.QtPrintSupport',

        # ── Core libraries ────────────────────────────────────────────
        'sqlalchemy',
        'sqlalchemy.orm',
        'sqlalchemy.ext.declarative',
        'sqlite3',
        'reportlab',
        'reportlab.lib',
        'reportlab.lib.pagesizes',
        'reportlab.lib.units',
        'reportlab.lib.colors',
        'reportlab.lib.styles',
        'reportlab.lib.enums',
        'reportlab.platypus',
        'reportlab.platypus.tables',
        'reportlab.platypus.paragraph',
        'reportlab.pdfgen',
        'reportlab.pdfgen.canvas',
        'reportlab.pdfbase',
        'reportlab.pdfbase.ttfonts',
        'reportlab.pdfbase.pdfmetrics',

        # ── App — top-level ───────────────────────────────────────────
        'app',
        'app.config',

        # ── App — database ────────────────────────────────────────────
        'app.database',
        'app.database.engine',
        'app.database.migrations',

        # ── App — models ──────────────────────────────────────────────
        'app.models',
        'app.models.customer',
        'app.models.measurement',
        'app.models.order',
        'app.models.payment',
        'app.models.expense',
        'app.models.settings',
        'app.models.worker',
        'app.models.stock',

        # ── App — repositories ────────────────────────────────────────
        'app.repositories',
        'app.repositories.customer_repo',
        'app.repositories.expense_repo',
        'app.repositories.measurement_repo',
        'app.repositories.order_repo',
        'app.repositories.payment_repo',
        'app.repositories.settings_repo',
        'app.repositories.stock_repo',

        # ── App — services ────────────────────────────────────────────
        'app.services',
        'app.services.backup_service',
        'app.services.customer_service',
        'app.services.dictation_service',
        'app.services.expense_service',
        'app.services.measurement_service',
        'app.services.order_service',
        'app.services.payment_service',
        'app.services.print_service',
        'app.services.report_service',
        'app.services.stock_service',
        'app.services.whatsapp_service',
        'app.services.worker_service',

        # ── App — printing ────────────────────────────────────────────
        'app.printing',
        'app.printing.receipt_printer',
        'app.printing.report_printer',
        'app.printing.stitching_slip',

        # ── App — UI ──────────────────────────────────────────────────
        'app.ui',
        'app.ui.theme',
        'app.ui.web_bridge',
        'app.ui.main_window',
        'app.ui.backup',
        'app.ui.backup.backup_page',
        'app.ui.customers',
        'app.ui.customers.customers_page',
        'app.ui.customers.customer_detail',
        'app.ui.customers.customer_dialog',
        'app.ui.dashboard',
        'app.ui.dashboard.dashboard_page',
        'app.ui.deliveries',
        'app.ui.deliveries.deliveries_page',
        'app.ui.expenses',
        'app.ui.expenses.expenses_page',
        'app.ui.first_run',
        'app.ui.first_run.setup_wizard',
        'app.ui.measurements',
        'app.ui.measurements.measurements_page',
        'app.ui.measurements.measurement_dialog',
        'app.ui.orders',
        'app.ui.orders.orders_page',
        'app.ui.orders.order_detail',
        'app.ui.orders.new_order_wizard',
        'app.ui.payments',
        'app.ui.payments.payments_page',
        'app.ui.payments.payment_dialog',
        'app.ui.reports',
        'app.ui.reports.reports_page',
        'app.ui.settings',
        'app.ui.settings.settings_page',
        'app.ui.widgets',
        'app.ui.widgets.cards',
        'app.ui.widgets.dialogs',
        'app.ui.widgets.header',
        'app.ui.widgets.notification',
        'app.ui.widgets.sidebar',
        'app.ui.widgets.status_badge',

        # ── App — utils ───────────────────────────────────────────────
        'app.utils',
        'app.utils.formatters',
        'app.utils.logger',
        'app.utils.validators',

        # ── App — web ─────────────────────────────────────────────────
        'app.web',
        'app.web.server',
        'app.web.tunnel',

        # ── Third-party ───────────────────────────────────────────────
        'pyngrok',
        'pyngrok.ngrok',
        'fastapi',
        'fastapi.responses',
        'fastapi.staticfiles',
        'fastapi.middleware',
        'fastapi.middleware.cors',
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.http.h11_impl',
        'uvicorn.protocols.http.httptools_impl',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        'pydantic',
        'pydantic.fields',
        'qrcode',
        'qrcode.image',
        'qrcode.image.pil',
        'urllib.parse',
        'speech_recognition',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'PIL.ImageFont',

        # ── Python stdlib often missed ────────────────────────────────
        'json',
        'datetime',
        'shutil',
        'threading',
        'platform',
        'logging',
        'traceback',
        'enum',
        'decimal',
        'io',
        'base64',
        'hashlib',
        'uuid',
        'subprocess',
        'asyncio',
        'http',
        'http.server',
        'multiprocessing',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Haroon Tailor',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='app/assets/www/img/logo.ico',
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='Haroon Tailor',
)
